spring.application.name=nexusmarket

# =========================================================
# MySQL (persistencia relacional)
# =========================================================
spring.datasource.url=jdbc:mysql://localhost:3306/nexusmarket?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# MongoDB (auditoría de eventos de dominio)
# =========================================================
spring.data.mongodb.uri=mongodb://localhost:27017/nexusmarket
